name: Deploy to GitHub Pages (gh-pages)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          # NOTE: If your repository disallows the default GITHUB_TOKEN from creating branches,
          # create a Personal Access Token (classic) with `repo` scope and add it as repository secret
          # named `GH_PAGES_PAT`, then set github_token to that secret below.
          github_token: ${{ secrets.GH_PAGES_PAT }}
          publish_dir: ./
          publish_branch: gh-pages
